#!/usr/bin/env python3
"""Command-line workspace, evidence, indicator-registry, and program-measurement, review-workflow, and analysis operations for v1.7.0."""
from __future__ import annotations
import argparse,json,sys
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path: sys.path.insert(0,str(ROOT))
from python.global_impact_repository import SQLiteImpactRepository
from python.global_impact_service import ImpactApplicationService


def read_json(path:str): return json.loads(Path(path).read_text(encoding='utf-8'))
def emit(value): print(json.dumps(value,indent=2,ensure_ascii=False,default=lambda o:o.__dict__))

def main()->int:
    parser=argparse.ArgumentParser(description='Global Impact Catalyst repository, evidence, indicator-registry, and program-measurement, review-workflow, and analysis CLI')
    parser.add_argument('--database',default='outputs/global-impact-catalyst.sqlite3')
    sub=parser.add_subparsers(dest='command',required=True)
    sub.add_parser('init')
    create=sub.add_parser('create'); create.add_argument('--input',required=True); create.add_argument('--generated-at'); create.add_argument('--allow-invalid',action='store_true')
    imp=sub.add_parser('import'); imp.add_argument('--input',required=True); imp.add_argument('--generated-at')
    listing=sub.add_parser('list'); listing.add_argument('--workspace-id'); listing.add_argument('--search',default=''); listing.add_argument('--status'); listing.add_argument('--include-archived',action='store_true')
    show=sub.add_parser('show'); show.add_argument('--initiative-id',required=True)
    duplicate=sub.add_parser('duplicate'); duplicate.add_argument('--initiative-id',required=True); duplicate.add_argument('--name',required=True); duplicate.add_argument('--workspace-name'); duplicate.add_argument('--generated-at')
    archive=sub.add_parser('archive'); archive.add_argument('--initiative-id',required=True); archive.add_argument('--revision',required=True,type=int)
    restore=sub.add_parser('restore'); restore.add_argument('--initiative-id',required=True); restore.add_argument('--revision',required=True,type=int)
    export=sub.add_parser('export'); export.add_argument('--workspace-id',required=True); export.add_argument('--output',required=True)
    restore_bundle=sub.add_parser('restore-bundle'); restore_bundle.add_argument('--input',required=True)
    backup=sub.add_parser('backup'); backup.add_argument('--output',required=True)
    sources=sub.add_parser('sources'); sources.add_argument('--workspace-id'); sources.add_argument('--initiative-id'); sources.add_argument('--search',default='')
    add_source=sub.add_parser('add-source'); add_source.add_argument('--input',required=True); add_source.add_argument('--workspace-id',required=True); add_source.add_argument('--initiative-id'); add_source.add_argument('--expected-revision',type=int)
    version=sub.add_parser('add-source-version'); version.add_argument('--source-id',required=True); version.add_argument('--file',required=True); version.add_argument('--label',default=''); version.add_argument('--mime-type',default='application/octet-stream'); version.add_argument('--captured-by',default='cli')
    evidence=sub.add_parser('capture-evidence'); evidence.add_argument('--source-id',required=True); evidence.add_argument('--input',required=True)
    dataset=sub.add_parser('register-dataset'); dataset.add_argument('--source-id',required=True); dataset.add_argument('--input',required=True)
    link=sub.add_parser('link-evidence'); link.add_argument('--claim-id',required=True); link.add_argument('--evidence-id',required=True); link.add_argument('--relationship',default='supports'); link.add_argument('--strength',default='direct'); link.add_argument('--notes',default='')
    chain=sub.add_parser('evidence-chain'); chain.add_argument('--initiative-id',required=True); chain.add_argument('--output')
    units=sub.add_parser('units'); units.add_argument('--workspace-id'); units.add_argument('--dimension'); units.add_argument('--search',default='')
    add_unit=sub.add_parser('add-unit'); add_unit.add_argument('--input',required=True); add_unit.add_argument('--workspace-id'); add_unit.add_argument('--expected-revision',type=int)
    indicators=sub.add_parser('indicators'); indicators.add_argument('--workspace-id',required=True); indicators.add_argument('--search',default='')
    add_indicator=sub.add_parser('add-indicator'); add_indicator.add_argument('--input',required=True); add_indicator.add_argument('--workspace-id',required=True); add_indicator.add_argument('--expected-revision',type=int)
    add_baseline=sub.add_parser('add-baseline'); add_baseline.add_argument('--input',required=True); add_baseline.add_argument('--workspace-id',required=True)
    compute_baseline=sub.add_parser('compute-baseline'); compute_baseline.add_argument('--baseline-model-id',required=True); compute_baseline.add_argument('--observations',required=True,help='JSON file containing values or observation objects')
    add_target=sub.add_parser('add-target'); add_target.add_argument('--input',required=True); add_target.add_argument('--workspace-id',required=True)
    evaluate_target=sub.add_parser('evaluate-target'); evaluate_target.add_argument('--target-model-id',required=True); evaluate_target.add_argument('--baseline-value',type=float); evaluate_target.add_argument('--progress-fraction',type=float); evaluate_target.add_argument('--period-label')
    add_method=sub.add_parser('add-method'); add_method.add_argument('--input',required=True); add_method.add_argument('--workspace-id',required=True)
    registry=sub.add_parser('indicator-registry'); registry.add_argument('--workspace-id',required=True); registry.add_argument('--output')
    add_result=sub.add_parser('add-impact-result'); add_result.add_argument('--input',required=True); add_result.add_argument('--workspace-id',required=True); add_result.add_argument('--initiative-id',required=True)
    add_observation=sub.add_parser('add-observation'); add_observation.add_argument('--input',required=True); add_observation.add_argument('--workspace-id',required=True); add_observation.add_argument('--initiative-id',required=True)
    series=sub.add_parser('observation-series'); series.add_argument('--initiative-id',required=True); series.add_argument('--indicator-id',required=True); series.add_argument('--output')
    add_beneficiary=sub.add_parser('add-beneficiary-definition'); add_beneficiary.add_argument('--input',required=True); add_beneficiary.add_argument('--workspace-id',required=True); add_beneficiary.add_argument('--initiative-id',required=True)
    beneficiary_observation=sub.add_parser('add-beneficiary-observation'); beneficiary_observation.add_argument('--definition-id',required=True); beneficiary_observation.add_argument('--input',required=True)
    beneficiary_summary=sub.add_parser('beneficiary-summary'); beneficiary_summary.add_argument('--initiative-id',required=True); beneficiary_summary.add_argument('--period-label')
    add_financial=sub.add_parser('add-financial-record'); add_financial.add_argument('--input',required=True); add_financial.add_argument('--workspace-id',required=True); add_financial.add_argument('--initiative-id',required=True)
    financial_summary=sub.add_parser('financial-summary'); financial_summary.add_argument('--initiative-id',required=True); financial_summary.add_argument('--period-label'); financial_summary.add_argument('--reporting-currency')
    cost_metric=sub.add_parser('cost-metric'); cost_metric.add_argument('--initiative-id',required=True); cost_metric.add_argument('--denominator-type',required=True,choices=['beneficiary','output','outcome']); cost_metric.add_argument('--denominator-id'); cost_metric.add_argument('--period-label'); cost_metric.add_argument('--reporting-currency')
    add_factor=sub.add_parser('add-external-factor'); add_factor.add_argument('--input',required=True); add_factor.add_argument('--workspace-id',required=True); add_factor.add_argument('--initiative-id',required=True)
    add_note=sub.add_parser('add-contribution-note'); add_note.add_argument('--input',required=True); add_note.add_argument('--workspace-id',required=True); add_note.add_argument('--initiative-id',required=True)
    add_outcome_portfolio=sub.add_parser('add-outcome-portfolio'); add_outcome_portfolio.add_argument('--input',required=True); add_outcome_portfolio.add_argument('--workspace-id',required=True)
    add_outcome_member=sub.add_parser('add-outcome-member'); add_outcome_member.add_argument('--portfolio-id',required=True); add_outcome_member.add_argument('--input',required=True)
    aggregate_outcome=sub.add_parser('aggregate-outcome-portfolio'); aggregate_outcome.add_argument('--portfolio-id',required=True); aggregate_outcome.add_argument('--period-label',default=''); aggregate_outcome.add_argument('--period-start'); aggregate_outcome.add_argument('--period-end'); aggregate_outcome.add_argument('--output')
    measurement=sub.add_parser('measurement-repository'); measurement.add_argument('--workspace-id',required=True); measurement.add_argument('--output')
    workflow=sub.add_parser('review-workflow'); workflow.add_argument('--workspace-id',required=True); workflow.add_argument('--output')
    add_role=sub.add_parser('add-review-role'); add_role.add_argument('--workspace-id',required=True); add_role.add_argument('--input',required=True)
    assign=sub.add_parser('assign-review'); assign.add_argument('--workspace-id',required=True); assign.add_argument('--initiative-id',required=True); assign.add_argument('--input',required=True)
    comment=sub.add_parser('add-review-comment'); comment.add_argument('--assignment-id',required=True); comment.add_argument('--input',required=True)
    resolve_comment=sub.add_parser('resolve-review-comment'); resolve_comment.add_argument('--comment-id',required=True); resolve_comment.add_argument('--resolution',default='resolved',choices=['resolved','wont_fix'])
    assess=sub.add_parser('assess-quality'); assess.add_argument('--workspace-id',required=True); assess.add_argument('--initiative-id',required=True); assess.add_argument('--assignment-id'); assess.add_argument('--input',required=True)
    decide=sub.add_parser('review-decision'); decide.add_argument('--assignment-id',required=True); decide.add_argument('--decision',required=True,choices=['approve','request_changes','reject','abstain']); decide.add_argument('--rationale',required=True); decide.add_argument('--reviewer-id')
    correction=sub.add_parser('open-correction'); correction.add_argument('--workspace-id',required=True); correction.add_argument('--initiative-id',required=True); correction.add_argument('--input',required=True)
    publication=sub.add_parser('create-publication'); publication.add_argument('--workspace-id',required=True); publication.add_argument('--initiative-id',required=True); publication.add_argument('--input',required=True)
    publish=sub.add_parser('publish'); publish.add_argument('--publication-id',required=True); publish.add_argument('--quality-threshold',type=float,default=60.0)
    withdraw=sub.add_parser('withdraw-publication'); withdraw.add_argument('--publication-id',required=True); withdraw.add_argument('--reason',required=True)
    trend=sub.add_parser('trend'); trend.add_argument('--initiative-id',required=True); trend.add_argument('--indicator-id',required=True); trend.add_argument('--target-unit-id'); trend.add_argument('--include-partial',action='store_true'); trend.add_argument('--missing-policy',choices=['block','exclude','warn'],default='exclude'); trend.add_argument('--persist',action='store_true')
    add_benchmark=sub.add_parser('add-benchmark'); add_benchmark.add_argument('--input',required=True); add_benchmark.add_argument('--workspace-id',required=True); add_benchmark.add_argument('--expected-revision',type=int)
    compare_benchmark=sub.add_parser('compare-benchmark'); compare_benchmark.add_argument('--initiative-id',required=True); compare_benchmark.add_argument('--indicator-id',required=True); compare_benchmark.add_argument('--benchmark-id',required=True); compare_benchmark.add_argument('--observation-id'); compare_benchmark.add_argument('--period-policy',choices=['exact','overlap','same_label','ignore'],default='overlap'); compare_benchmark.add_argument('--geography-policy',choices=['exact','warn','ignore'],default='warn'); compare_benchmark.add_argument('--population-policy',choices=['exact','warn','ignore'],default='warn'); compare_benchmark.add_argument('--direction',choices=['higher_is_better','lower_is_better','neutral'],default='neutral'); compare_benchmark.add_argument('--persist',action='store_true')
    add_comparison_set=sub.add_parser('add-comparison-set'); add_comparison_set.add_argument('--input',required=True); add_comparison_set.add_argument('--workspace-id',required=True); add_comparison_set.add_argument('--expected-revision',type=int)
    add_comparison_member=sub.add_parser('add-comparison-member'); add_comparison_member.add_argument('--comparison-set-id',required=True); add_comparison_member.add_argument('--input',required=True)
    run_comparison_set=sub.add_parser('run-comparison-set'); run_comparison_set.add_argument('--comparison-set-id',required=True); run_comparison_set.add_argument('--persist',action='store_true')
    add_uncertainty=sub.add_parser('add-uncertainty'); add_uncertainty.add_argument('--input',required=True); add_uncertainty.add_argument('--workspace-id',required=True); add_uncertainty.add_argument('--expected-revision',type=int)
    apply_uncertainty=sub.add_parser('apply-uncertainty'); apply_uncertainty.add_argument('--uncertainty-model-id',required=True); apply_uncertainty.add_argument('--value',required=True,type=float)
    add_scenario=sub.add_parser('add-scenario'); add_scenario.add_argument('--input',required=True); add_scenario.add_argument('--workspace-id',required=True); add_scenario.add_argument('--initiative-id',required=True); add_scenario.add_argument('--expected-revision',type=int)
    evaluate_scenario=sub.add_parser('evaluate-scenario'); evaluate_scenario.add_argument('--scenario-id',required=True); evaluate_scenario.add_argument('--uncertainty-model-id'); evaluate_scenario.add_argument('--overrides'); evaluate_scenario.add_argument('--no-persist',action='store_true')
    sensitivity=sub.add_parser('sensitivity'); sensitivity.add_argument('--scenario-id',required=True); sensitivity.add_argument('--ranges',required=True)
    target_trajectory=sub.add_parser('target-trajectory'); target_trajectory.add_argument('--initiative-id',required=True); target_trajectory.add_argument('--indicator-id',required=True); target_trajectory.add_argument('--target-model-id',required=True); target_trajectory.add_argument('--persist',action='store_true')
    analysis_repository=sub.add_parser('analysis-repository'); analysis_repository.add_argument('--workspace-id',required=True); analysis_repository.add_argument('--output')
    sub.add_parser('summary')
    args=parser.parse_args()
    with SQLiteImpactRepository(args.database) as repository:
        service=ImpactApplicationService(repository)
        if args.command=='init': emit({'database':args.database,'schema_version':repository.schema_version,'migrations':repository.applied_migrations()})
        elif args.command=='create': emit(service.create_initiative(read_json(args.input),generated_at=args.generated_at,allow_invalid=args.allow_invalid))
        elif args.command=='import': emit(service.import_document(read_json(args.input),generated_at=args.generated_at).__dict__)
        elif args.command=='list': emit(service.list_initiatives(workspace_id=args.workspace_id,search=args.search,lifecycle_status=args.status,include_archived=args.include_archived))
        elif args.command=='show': emit(repository.get_contract(initiative_id=args.initiative_id))
        elif args.command=='duplicate': emit(service.duplicate_initiative(args.initiative_id,new_name=args.name,target_workspace_name=args.workspace_name,generated_at=args.generated_at))
        elif args.command=='archive': emit(repository.archive_entity('initiative',args.initiative_id,expected_revision=args.revision))
        elif args.command=='restore': emit(repository.restore_entity('initiative',args.initiative_id,expected_revision=args.revision))
        elif args.command=='export': emit({'output':str(Path(args.output)),'bundle':service.export_workspace(args.workspace_id,args.output)})
        elif args.command=='restore-bundle': emit(service.restore_workspace(read_json(args.input)))
        elif args.command=='backup': emit({'backup':str(repository.backup_database(args.output))})
        elif args.command=='sources': emit(repository.list_sources(workspace_id=args.workspace_id,initiative_id=args.initiative_id,search=args.search))
        elif args.command=='add-source': emit(service.register_source(read_json(args.input),workspace_id=args.workspace_id,initiative_id=args.initiative_id,expected_revision=args.expected_revision,actor='cli'))
        elif args.command=='add-source-version':
            path=Path(args.file); emit(service.add_source_version(args.source_id,version_label=args.label,payload=path.read_bytes(),mime_type=args.mime_type,size_bytes=path.stat().st_size,captured_by=args.captured_by,metadata={'filename':path.name}))
        elif args.command=='capture-evidence': emit(service.capture_evidence(args.source_id,**read_json(args.input)))
        elif args.command=='register-dataset': emit(service.register_dataset(args.source_id,read_json(args.input),actor='cli'))
        elif args.command=='link-evidence': emit(service.link_claim_evidence(args.claim_id,args.evidence_id,relationship=args.relationship,strength=args.strength,notes=args.notes,linked_by='cli'))
        elif args.command=='evidence-chain': emit(service.evidence_chain(args.initiative_id,args.output))
        elif args.command=='units': emit(repository.list_units(workspace_id=args.workspace_id,dimension=args.dimension,search=args.search))
        elif args.command=='add-unit': emit(service.register_unit(read_json(args.input),workspace_id=args.workspace_id,expected_revision=args.expected_revision,actor='cli'))
        elif args.command=='indicators': emit(repository.list_indicator_definitions(workspace_id=args.workspace_id,search=args.search))
        elif args.command=='add-indicator': emit(service.register_indicator_definition(read_json(args.input),workspace_id=args.workspace_id,expected_revision=args.expected_revision,actor='cli'))
        elif args.command=='add-baseline': emit(service.register_baseline_model(read_json(args.input),workspace_id=args.workspace_id,actor='cli'))
        elif args.command=='compute-baseline': emit(repository.compute_baseline(args.baseline_model_id,read_json(args.observations)))
        elif args.command=='add-target': emit(service.register_target_model(read_json(args.input),workspace_id=args.workspace_id,actor='cli'))
        elif args.command=='evaluate-target': emit(repository.evaluate_target(args.target_model_id,baseline_value=args.baseline_value,progress_fraction=args.progress_fraction,period_label=args.period_label))
        elif args.command=='add-method': emit(service.register_method_definition(read_json(args.input),workspace_id=args.workspace_id,actor='cli'))
        elif args.command=='indicator-registry': emit(service.indicator_registry(args.workspace_id,args.output))
        elif args.command=='add-impact-result': emit(service.register_impact_result(read_json(args.input),workspace_id=args.workspace_id,initiative_id=args.initiative_id,actor='cli'))
        elif args.command=='add-observation': emit(service.record_observation(read_json(args.input),workspace_id=args.workspace_id,initiative_id=args.initiative_id,actor='cli'))
        elif args.command=='observation-series': emit(service.observation_series(args.initiative_id,args.indicator_id,args.output))
        elif args.command=='add-beneficiary-definition': emit(service.register_beneficiary_definition(read_json(args.input),workspace_id=args.workspace_id,initiative_id=args.initiative_id,actor='cli'))
        elif args.command=='add-beneficiary-observation': emit(service.record_beneficiary_observation(args.definition_id,read_json(args.input),actor='cli'))
        elif args.command=='beneficiary-summary': emit(repository.beneficiary_summary(args.initiative_id,period_label=args.period_label))
        elif args.command=='add-financial-record': emit(service.record_financial_record(read_json(args.input),workspace_id=args.workspace_id,initiative_id=args.initiative_id,actor='cli'))
        elif args.command=='financial-summary': emit(repository.financial_summary(args.initiative_id,period_label=args.period_label,reporting_currency=args.reporting_currency))
        elif args.command=='cost-metric': emit(repository.calculate_cost_metric(args.initiative_id,denominator_type=args.denominator_type,denominator_id=args.denominator_id,period_label=args.period_label,reporting_currency=args.reporting_currency))
        elif args.command=='add-external-factor': emit(repository.add_external_factor(read_json(args.input),workspace_id=args.workspace_id,initiative_id=args.initiative_id,actor='cli'))
        elif args.command=='add-contribution-note': emit(repository.add_contribution_note(read_json(args.input),workspace_id=args.workspace_id,initiative_id=args.initiative_id,actor='cli'))
        elif args.command=='add-outcome-portfolio': emit(service.create_outcome_portfolio(read_json(args.input),workspace_id=args.workspace_id,actor='cli'))
        elif args.command=='add-outcome-member': emit(repository.add_outcome_portfolio_member(args.portfolio_id,read_json(args.input),actor='cli'))
        elif args.command=='aggregate-outcome-portfolio':
            result=repository.aggregate_outcome_portfolio(args.portfolio_id,period_start=args.period_start,period_end=args.period_end,period_label=args.period_label,actor='cli')
            if args.output: Path(args.output).write_text(json.dumps(result,indent=2,ensure_ascii=False)+'\n',encoding='utf-8')
            emit(result)
        elif args.command=='measurement-repository': emit(service.measurement_repository(args.workspace_id,args.output))
        elif args.command=='review-workflow': emit(service.review_workflow(args.workspace_id,args.output))
        elif args.command=='add-review-role': emit(service.register_workflow_role(read_json(args.input),workspace_id=args.workspace_id,actor='cli'))
        elif args.command=='assign-review': emit(service.create_review_assignment(read_json(args.input),workspace_id=args.workspace_id,initiative_id=args.initiative_id,actor='cli'))
        elif args.command=='add-review-comment': emit(service.add_review_comment(args.assignment_id,read_json(args.input),actor='cli'))
        elif args.command=='resolve-review-comment': emit(repository.resolve_review_comment(args.comment_id,resolution_status=args.resolution,actor='cli'))
        elif args.command=='assess-quality': emit(service.submit_quality_assessment(read_json(args.input),workspace_id=args.workspace_id,initiative_id=args.initiative_id,assignment_id=args.assignment_id,actor='cli'))
        elif args.command=='review-decision': emit(service.record_approval_decision(args.assignment_id,args.decision,rationale=args.rationale,reviewer_id=args.reviewer_id,actor=args.reviewer_id or 'cli'))
        elif args.command=='open-correction': emit(service.open_correction(read_json(args.input),workspace_id=args.workspace_id,initiative_id=args.initiative_id,actor='cli'))
        elif args.command=='create-publication': emit(service.create_publication(read_json(args.input),workspace_id=args.workspace_id,initiative_id=args.initiative_id,actor='cli'))
        elif args.command=='publish': emit(service.publish(args.publication_id,actor='cli',quality_threshold=args.quality_threshold))
        elif args.command=='withdraw-publication': emit(service.withdraw_publication(args.publication_id,reason=args.reason,actor='cli'))
        elif args.command=='trend': emit(service.analyze_trend(args.initiative_id,args.indicator_id,target_unit_id=args.target_unit_id,include_partial=args.include_partial,missing_policy=args.missing_policy,actor='cli',persist=args.persist))
        elif args.command=='add-benchmark': emit(service.register_benchmark(read_json(args.input),workspace_id=args.workspace_id,expected_revision=args.expected_revision,actor='cli'))
        elif args.command=='compare-benchmark': emit(service.compare_to_benchmark(args.initiative_id,args.indicator_id,args.benchmark_id,observation_id=args.observation_id,period_policy=args.period_policy,geography_policy=args.geography_policy,population_policy=args.population_policy,direction=args.direction,actor='cli',persist=args.persist))
        elif args.command=='add-comparison-set': emit(service.create_comparison_set(read_json(args.input),workspace_id=args.workspace_id,expected_revision=args.expected_revision,actor='cli'))
        elif args.command=='add-comparison-member': emit(service.add_comparison_member(args.comparison_set_id,read_json(args.input),actor='cli'))
        elif args.command=='run-comparison-set': emit(service.run_comparison_set(args.comparison_set_id,actor='cli',persist=args.persist))
        elif args.command=='add-uncertainty': emit(service.register_uncertainty_model(read_json(args.input),workspace_id=args.workspace_id,expected_revision=args.expected_revision,actor='cli'))
        elif args.command=='apply-uncertainty': emit(repository.apply_uncertainty(args.uncertainty_model_id,args.value))
        elif args.command=='add-scenario': emit(service.register_scenario(read_json(args.input),workspace_id=args.workspace_id,initiative_id=args.initiative_id,expected_revision=args.expected_revision,actor='cli'))
        elif args.command=='evaluate-scenario': emit(service.evaluate_scenario(args.scenario_id,parameter_overrides=read_json(args.overrides) if args.overrides else None,uncertainty_model_id=args.uncertainty_model_id,actor='cli',persist=not args.no_persist))
        elif args.command=='sensitivity': emit(service.run_sensitivity_analysis(args.scenario_id,read_json(args.ranges),actor='cli'))
        elif args.command=='target-trajectory': emit(service.compare_observations_to_target(args.initiative_id,args.indicator_id,args.target_model_id,actor='cli',persist=args.persist))
        elif args.command=='analysis-repository': emit(service.analysis_repository(args.workspace_id,args.output))
        elif args.command=='summary': emit(repository.repository_summary())
    return 0
if __name__=='__main__': raise SystemExit(main())
